/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "SQLQuery"
 * 	found in "SQLQuery.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_ASNColumnRefList_H_
#define	_ASNColumnRefList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASNColumnRefItem;

/* ASNColumnRefList */
typedef struct ASNColumnRefList {
	A_SEQUENCE_OF(struct ASNColumnRefItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASNColumnRefList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASNColumnRefList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ASNColumnRefItem.h"

#endif	/* _ASNColumnRefList_H_ */
