/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "SQLQuery"
 * 	found in "SQLQuery.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_ASNSelectStmt_H_
#define	_ASNSelectStmt_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASNResTarget;
struct ASNFromClause;

/* ASNSelectStmt */
typedef struct ASNSelectStmt {
	struct targets {
		A_SEQUENCE_OF(struct ASNResTarget) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} targets;
	struct fromClause {
		A_SEQUENCE_OF(struct ASNFromClause) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *fromClause;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASNSelectStmt_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASNSelectStmt;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ASNResTarget.h"
#include "ASNFromClause.h"

#endif	/* _ASNSelectStmt_H_ */
