/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "SQLQuery"
 * 	found in "SQLQuery.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#include <asn_internal.h>

#include "ASNExpression.h"

static asn_TYPE_member_t asn_MBR_ASNExpression_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASNExpression, choice.intConst),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"intConst"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASNExpression, choice.floatConst),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_NativeReal,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"floatConst"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASNExpression, choice.stringConst),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASNString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"stringConst"
		},
	{ ATF_POINTER, 0, offsetof(struct ASNExpression, choice.binaryExpr),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ASNBinaryExpression,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"binaryExpr"
		},
};
static asn_TYPE_tag2member_t asn_MAP_ASNExpression_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* intConst at 46 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* floatConst at 47 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* stringConst at 48 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* binaryExpr at 50 */
};
static asn_CHOICE_specifics_t asn_SPC_ASNExpression_specs_1 = {
	sizeof(struct ASNExpression),
	offsetof(struct ASNExpression, _asn_ctx),
	offsetof(struct ASNExpression, present),
	sizeof(((struct ASNExpression *)0)->present),
	asn_MAP_ASNExpression_tag2el_1,
	4,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static asn_per_constraints_t asn_PER_ASNExpression_constr_1 = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
asn_TYPE_descriptor_t asn_DEF_ASNExpression = {
	"ASNExpression",
	"ASNExpression",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_ASNExpression_constr_1,
	asn_MBR_ASNExpression_1,
	4,	/* Elements count */
	&asn_SPC_ASNExpression_specs_1	/* Additional specs */
};

