/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "SQLQuery"
 * 	found in "SQLQuery.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_ASNFromClause_H_
#define	_ASNFromClause_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ASNRangeVar;

/* ASNFromClause */
typedef struct ASNFromClause {
	A_SEQUENCE_OF(struct ASNRangeVar) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASNFromClause_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASNFromClause;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ASNRangeVar.h"

#endif	/* _ASNFromClause_H_ */
