/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "SQLQuery"
 * 	found in "SQLQuery.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#include <asn_internal.h>

#include "ASNPlusExpression.h"

static asn_TYPE_member_t asn_MBR_ASNPlusExpression_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASNPlusExpression, lhs),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ASNExpression,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"lhs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASNPlusExpression, rhs),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_ASNExpression,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rhs"
		},
};
static ber_tlv_tag_t asn_DEF_ASNPlusExpression_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ASNPlusExpression_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 1 }, /* intConst at 46 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, -1, 0 }, /* intConst at 46 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 1 }, /* floatConst at 47 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, -1, 0 }, /* floatConst at 47 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 1 }, /* stringConst at 48 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, -1, 0 }, /* stringConst at 48 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 1 }, /* binaryExpr at 50 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, -1, 0 } /* binaryExpr at 50 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ASNPlusExpression_specs_1 = {
	sizeof(struct ASNPlusExpression),
	offsetof(struct ASNPlusExpression, _asn_ctx),
	asn_MAP_ASNPlusExpression_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ASNPlusExpression = {
	"ASNPlusExpression",
	"ASNPlusExpression",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ASNPlusExpression_tags_1,
	sizeof(asn_DEF_ASNPlusExpression_tags_1)
		/sizeof(asn_DEF_ASNPlusExpression_tags_1[0]), /* 1 */
	asn_DEF_ASNPlusExpression_tags_1,	/* Same as above */
	sizeof(asn_DEF_ASNPlusExpression_tags_1)
		/sizeof(asn_DEF_ASNPlusExpression_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ASNPlusExpression_1,
	2,	/* Elements count */
	&asn_SPC_ASNPlusExpression_specs_1	/* Additional specs */
};

