/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "SQLQuery"
 * 	found in "SQLQuery.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#ifndef	_ASNResTarget_H_
#define	_ASNResTarget_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "ASNColumnRef.h"
#include "ASNExpression.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ASNResTarget_PR {
	ASNResTarget_PR_NOTHING,	/* No components present */
	ASNResTarget_PR_star,
	ASNResTarget_PR_columnRef,
	ASNResTarget_PR_resTargetExpression
} ASNResTarget_PR;

/* Forward declarations */
struct ASNString;

/* ASNResTarget */
typedef struct ASNResTarget {
	ASNResTarget_PR present;
	union ASNResTarget_u {
		NULL_t	 star;
		ASNColumnRef_t	 columnRef;
		struct resTargetExpression {
			ASNExpression_t	 expr;
			struct ASNString	*colLabel	/* OPTIONAL */;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} resTargetExpression;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ASNResTarget_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ASNResTarget;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ASNString.h"

#endif	/* _ASNResTarget_H_ */
