/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "SQLQuery"
 * 	found in "SQLQuery.asn1"
 * 	`asn1c -fskeletons-copy -fnative-types`
 */

#include <asn_internal.h>

#include "ASNString.h"

static asn_TYPE_member_t asn_MBR_ASNString_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ASNString, choice.utf8String),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"utf8String"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ASNString, choice.asciiString),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_IA5String,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"asciiString"
		},
};
static asn_TYPE_tag2member_t asn_MAP_ASNString_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* utf8String at 78 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* asciiString at 79 */
};
static asn_CHOICE_specifics_t asn_SPC_ASNString_specs_1 = {
	sizeof(struct ASNString),
	offsetof(struct ASNString, _asn_ctx),
	offsetof(struct ASNString, present),
	sizeof(((struct ASNString *)0)->present),
	asn_MAP_ASNString_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static asn_per_constraints_t asn_PER_ASNString_constr_1 = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
asn_TYPE_descriptor_t asn_DEF_ASNString = {
	"ASNString",
	"ASNString",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_ASNString_constr_1,
	asn_MBR_ASNString_1,
	2,	/* Elements count */
	&asn_SPC_ASNString_specs_1	/* Additional specs */
};

